[package]
name = "cargo-lock-reader-proc_macros"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
cargo-lock-reader-core ={ path = "../core" }

cargo-lock = "9.0.0"
lazy_static = "1.5.0"
